#!/bin/sh

################################################################################
#                                                                              #
# Advanced PNG Optimizer                                                       #
#                                                                              #
# Copyright (C) 2011-2014 Bamm Gabriana.                                       #
#                                                                              #
# This program is free software; you can redistribute it and/or modify         #
# it under the terms of the GNU General Public License as published by         #
# the Free Software Foundation; either version 2 of the License, or            #
# (at your option) any later version.                                          #
#                                                                              #
# This program is distributed in the hope that it will be useful,              #
# but WITHOUT ANY WARRANTY; without even the implied warranty of               #
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the                #
# GNU General Public License for more details.                                 #
#                                                                              #
# You should have received a copy of the GNU General Public License            #
# along with this program. If not, see <http://www.gnu.org/licenses/>          #
#                                                                              #
# On Debian systems, the complete text of the GNU General Public License       #
# version 2 and 3 can be found in                                              #
# "/usr/share/common-licenses/GPL-2" and "/usr/share/common-licenses/GPL-3".   #
#                                                                              #
################################################################################

exec="$(basename $0)"
ver="1.2"

# Process command line arguments.
for i do
	if [ -z "$i" ]; then false
	# All options.
	elif [ "$i" = "-q" -o "$i" = "--quiet"    ]; then	quiet="$i"
	elif [ "$i" = "-v" -o "$i" = "--verbose"  ]; then	verbose="$i"
	elif [ "$i" = "-d" -o "$i" = "--debug"    ]; then	debug="$i"
	elif [ "$i" = "-h" -o "$i" = "--help"     ]; then	help="$i"
	elif [ "$i" = "-V" -o "$i" = "--version"  ]; then	version="$i"
	# Remaining arguments.
	elif echo $i | grep " " >/dev/null; then
		args="$args \"$i\""
	else
		args="$args $i"
	fi
	_="$i"
done
args=$(echo $args | sed 's/^ //g')

main() {
	if [ $args ]; then
		if [ -d $args ]; then
			cd $args;
		else
			exit;
		fi
	fi
	apo $quiet $verbose
	apo $quiet $verbose
	apo $quiet $verbose --fixalpha
	apo $quiet $verbose alpha
	apo $quiet $verbose
}

showhelp() {
	echo "Usage: $exec [OPTION]..."
	echo ""
	echo "Make PNG images even smaller by running apo several times with the right"
	echo "options in the right order."
	echo ""
	echo "  -q, --quiet		don't display any output"
	echo "  -v, --verbose		show commands run on every file processed"
	echo "  -h, --help		display this help and exit"
	echo "  -V, --version		output version information and exit"
	echo ""
	echo "Report $exec bugs to Bamm Gabriana <bamm@distroastro.org>"
	echo "Distro Astro home page: <http://www.distroastro.org/>"
}

showversion() {
	echo "$exec $ver"
	echo "Copyright (C) 2011-2014 Bamm Gabriana."
	echo "License GPLv2+: GPL version 2 or later <http://gnu.org/licenses/gpl-2.0.html>."
	echo "This is free software: you are free to change and redistribute it."
	echo "There is NO WARRANTY, to the extent permitted by law."
	echo ""
	echo "Written by Bamm Gabriana."
}

[ -n "$help" ] && showhelp && exit
[ -n "$version" ] && showversion && exit
main

